//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Inventory_.dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.Device_Workplace = new HashSet<Device_Workplace>();
            this.DeviceParts = new HashSet<DeviceParts>();
        }
    
        public int Device_ID { get; set; }
        public Nullable<int> DeviceType_ID { get; set; }
        public string IP_Adress { get; set; }
        public Nullable<int> Department_ID { get; set; }
        public string DeviceName { get; set; }
        public Nullable<System.DateTime> DateOfCommissioning { get; set; }
        public string SerialNumber { get; set; }
        public string InventoryNumber { get; set; }
        public Nullable<int> Model_ID { get; set; }
        public Nullable<int> Office_ID { get; set; }
        public Nullable<bool> Exception { get; set; }
        public string Note { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual DeviceType DeviceType { get; set; }
        public virtual Model Model { get; set; }
        public virtual Office Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device_Workplace> Device_Workplace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceParts> DeviceParts { get; set; }
    }
}
