//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Inventory_.dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device_Workplace
    {
        public int Device_Workplace_ID { get; set; }
        public int Workplace_ID { get; set; }
        public int Device_ID { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Workplace Workplace { get; set; }
    }
}
