<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="dbg\**\*.cs" />
    <Content Remove="dbg\**\*" />
    <EmbeddedResource Remove="dbg\**\*" />
    <None Remove="dbg\**\*" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.3" />
    <PackageReference Include="Npgsql" Version="9.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.3" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="9.0.3" />
  </ItemGroup>
</Project>
